name: TryHackMe Update Badge

on:
  schedule:
    # Make it run every 24 hour
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  tryhackme-badge-update:
    name: <img src="https://tryhackme-badges.s3.amazonaws.com/muteshotgunguy.png" alt="TryHackMe">
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: axlfranklin/tryhackme-badge-workflow@main
        with:
          # Replace with your tryhackme username
          username: "muteshotgunguy"
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
